
ARG ARCH
FROM ghcr.io/jjl772/rtems-6-toolchains:${ARCH}

RUN apt-get update && apt-get install -y ca-certificates

COPY . /sb

ARG ARCH
ARG VERSION
RUN /sb/setup-rtems.bash -a ${ARCH} -p /opt/rtems/${VERSION} -c && rm -rf /sb
