
name: RTEMS Toolchain Docker Container

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ['powerpc', 'arm', 'i386', 'm68k', 'aarch64', 'riscv', 'x86_64']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/jjl772/rtems-6-toolchains:${{ matrix.arch }}
          build-args: |
            arch=${{ matrix.arch }}

